### ISSUE TITLE
Rename to isis-module-importexport-excel

### ISSUE THREAD

**Issue by oscarbou** [isisaddons/isis-module-excel#6]
This module is an implementation of an import/export feature that uses Excel as its repository mechanism.

I can easily envision an equivalent module for importing/exporting from an external database by means of JDBC, for example.

So, in order to clarify it's purpose and for future extensibility by means of a new isis-module, I would suggest to rename it.

Open to discussion.

**Comment by danhaywood** [comment]
As and when someone wants to write an import/export for JDBC, then we can revisit.  Until then, I'd rather leave things as they are.

**Comment by jcvanderwal** [comment]
A very trivial change that hurts our workflow. It's merely a wrapper around excel and it's not really extensible in the direction Oscar envisions. If there is a need for a generic import/export module I suggest creating a new module and move Excel capabilities in there.

Without objection I'm going to revert the name change.

**Comment by danhaywood** [comment]
um, I didn't make any change.

**Comment by jcvanderwal** [comment]
Associated commit activity with this ticket. Should have fetched my coffee first.

**Comment by danhaywood** [comment]
:-)

Those commits were for #8
